name: CI
on:
  push:
    branches:
      - main
    tags: [v*]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
env:
  PROJECT: 'datasance-pot'
  IMAGE_NAME: 'agent'
  POTCTL_VERSION: '1.0.0'
  CONTROLLER_IMAGE: 'iofog/controller:latest'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
#        cache: 'gradle'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: List contents of build directory before copy
      run: |
        ls -R ${{ github.workspace }}


  Integration:
    runs-on: ubuntu-20.04
    name: Integration
    needs: Build
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install jq
    - run: |
        curl https://packagecloud.io/install/repositories/datasance/potctl/script.deb.sh | sudo bash
        sudo apt-get install potctl=${{ env.POTCTL_VERSION }}
    - name: 'Install bats'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y bats
    - name: 'Deploy local ecn'
      shell: bash
      run: |
        sed -i "s|CONTROLLER_IMAGE=.*|CONTROLLER_IMAGE=\"${{ env.CONTROLLER_IMAGE }}\"|g" test/resources/env.sh
        sudo bash test/deploy_ecn.bash deployControlPlane
    - name: 'Run integration test'
      run: sudo bash test/run.bash
    - name: 'Delete ECN'
      if: always()
      run: sudo bash test/deploy_ecn.bash deleteECN

  Publish:
    runs-on: ubuntu-20.04
    needs: [Build, Integration]
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    name: Publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0
      - name: Set image tag
        shell: bash
        id: tags
        run: |
          if [[ ${{ github.ref_name }} =~ ^v.* ]] ; then
            VERSION=${{ github.ref_name }}
            echo "VERSION=${VERSION:1}" >> "${GITHUB_OUTPUT}"
          else
             VERSION=${{ steps.previoustag.outputs.tag }}
             echo "VERSION=${VERSION:1}-${{ github.run_number }}" >> "${GITHUB_OUTPUT}"
          fi

      - name: Login to Github Container Registry
        if: (github.ref == 'refs/heads/develop') || contains(github.ref_name, '^v.*')
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push to ghcr
        if: (github.ref == 'refs/heads/develop') || contains(github.ref_name, '^v.*')
        uses: docker/build-push-action@v3
        id: build_push_ghcr
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/datasance/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.VERSION }}
            ghcr.io/datasance/${{ env.IMAGE_NAME }}:latest
            ghcr.io/datasance/${{ env.IMAGE_NAME }}:main

      - name: Set up Ruby 3.1.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.4
      - run: |
          gem install --no-document fpm
          fpm -h
      - name: Install package_Cloud
        run: |
          gem install package_cloud
          package_cloud -h
      - name: get gradle version
        shell: bash
        id: version
        run: echo "version=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')"  >> "${GITHUB_OUTPUT}"
      - name: get package version
        shell: bash
        id: pkg_version
        run: |
          if [[ ${{ github.ref_name }} =~ ^v.* ]] ; then
            echo "version=${{ steps.version.outputs.version }}" >> "${GITHUB_OUTPUT}"
          else
            echo "version=${{ steps.version.outputs.version }}-${{ github.run_number }}" >> "${GITHUB_OUTPUT}"
          fi
      - run: echo ${{ steps.version.outputs.version }}
      - name: Create deb package
        shell: bash
        id: create_deb_package
        run: |
          cd packaging/iofog-agent
          fpm -s dir -d 'openjdk-8-jdk | openjdk-11-jdk' -d docker -t deb -n iofog-agent -v ${{ steps.pkg_version.outputs.version }} -a all --deb-no-default-config-files --after-install debian.sh --after-remove remove.sh --before-upgrade upgrade.sh --after-upgrade debian.sh etc usr
          echo "pkg created"
          ls
      - name: Create rpm package
        shell: bash
        id: create_rpm_package
        run: |
          cd packaging/iofog-agent
          fpm -s dir --depends java-11-openjdk -d docker-ce -t rpm -n iofog-agent -v ${{ steps.pkg_version.outputs.version }} -a all --rpm-os 'linux' --after-install rpm.sh --after-remove remove.sh --before-upgrade upgrade.sh --after-upgrade rpm.sh etc usr;
          echo "pkg created"
          ls
      - uses: actions/upload-artifact@v2
        name: Upload deb package
        with:
          name: deb-package
          path: packaging/iofog-agent/iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb

      - uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-text: ${{ steps.pkg_version.outputs.version }}
          '-': _
      - run: echo ${{ steps.sub.outputs.result }}

      - uses: actions/upload-artifact@v2
        name: Upload rpm package
        with:
          name: rpm-package
          path: packaging/iofog-agent/iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm

      - uses: actions/download-artifact@v2
        with:
          name: deb-package

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: any/any
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: ubuntu/focal
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: ubuntu/xenial
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: ubuntu/bionic
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB:  ubuntu/trusty
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: ubuntu/groovy
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: ubuntu/jammy
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: ubuntu/lunar
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB:  debian/stretch
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: debian/buster
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: debian/bullseye
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: debian/bookworm
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB:  raspbian/stretch
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: raspbian/buster
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish deb package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent_${{ steps.pkg_version.outputs.version }}_all.deb
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: raspbian/bullseye
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - uses: actions/download-artifact@v2
        with:
          name: rpm-package

      - name: Publish rpm package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: rpm_any/rpm_any
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish rpm package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: fedora/36
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish rpm package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: fedora/37
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish rpm package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: fedora/38
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish rpm package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: el/6
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish rpm package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: el/7
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish rpm package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: el/8
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Publish rpm package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: iofog-agent-${{ steps.sub.outputs.result }}-1.noarch.rpm
          PACKAGECLOUD-USERNAME: datasance
          PACKAGECLOUD-REPO: iofog-agent
          PACKAGECLOUD-DISTRIB: el/9
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}

      - name: Upload Agent Artifact
        uses: actions/upload-artifact@v3
        with:
          name: agent
          path: packaging/**/*


