name: test
on:
  push:
    branches:
      - main
    tags: [v*]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
env:
  PROJECT: 'datasance-pot'
  IMAGE_NAME: 'agent'
  POTCTL_VERSION: '1.0.0'
  CONTROLLER_IMAGE: 'iofog/controller:latest'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'write'
      id-token: 'write'
      packages: 'write'
    name: Build and Publish
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
#        cache: 'gradle'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build copyJar
    - name: List contents of build directory before copy
      run: |
        ls -R ${{ github.workspace }}